; Elemental types
;; NORMAL   EQU $00
;; FIGHTING EQU $01
;; FLYING   EQU $02
;; POISON   EQU $03
;; GROUND   EQU $04
;; ROCK     EQU $05
;; BUG      EQU $07
;; GHOST    EQU $08
;; STEEL    EQU $09
;; UNK_TYPE EQU $0A
;; FIRE     EQU $14
;; WATER    EQU $15
;; GRASS    EQU $16
;; ELECTRIC EQU $17
;; PSYCHIC  EQU $18
;; ICE      EQU $19
;; DRAGON   EQU $1A
;; DARK     EQU $1B
;; FAIRY    EQU $1C
NORMAL   EQU $00
FIGHTING EQU $01
FLYING   EQU $02
POISON   EQU $03
GROUND   EQU $04
ROCK     EQU $05
BUG      EQU $06
GHOST    EQU $07
STEEL    EQU $08
FIRE     EQU $09
WATER    EQU $0A
GRASS    EQU $0B
ELECTRIC EQU $0C
PSYCHIC  EQU $0D
ICE      EQU $0E
DRAGON   EQU $0F
DARK     EQU $10
FAIRY    EQU $11
UNK_TYPE EQU $12

; These are for the Physical Special split
PHYSICAL EQU $00
SPECIAL  EQU $01
OTHER_M  EQU $02
